language: elixir
elixir:
  - 1.4.5
otp_release:
  - 20.1
sudo: false
env:
  - MIX_ENV=test ECTO_PGSQL_USER=postgres ECTO_PGSQL_PASSWORD=
script:
  - mix test
after_script:
  - mix coveralls.travis
  - mix credo
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
